In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [64]:
df=pd.read_csv("student_multi.csv")

In [65]:
df.head()

  course_name  class_number  study_hours  last_exam_score  exam_score
0     History             1          4.1               65          61
1        Math             2          9.5               65          95
2        Math             3          7.5               55          90
3     History             1          6.2               72          80
4     Physics             2          2.0               56          45

In [66]:
df.tail()

     course_name  class_number  study_hours  last_exam_score  exam_score
1610        Math             3          5.7               83          67
1611     History             4          2.3               95          49
1612     Physics             1          0.7               48          32
1613     History             2          7.3               77          82
1614     Physics             1          0.5               33          20

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   course_name      1615 non-null   object
 1   class_number     1615 non-null   int64
 2   study_hours      1615 non-null   float64
 3   last_exam_score  1615 non-null   int64
 4   exam_score       1615 non-null   int64
dtypes: float64(1), int64(3), object(1)
memory usage: 63.2+ KB

In [68]:
df["course_name"].unique()
#also u can use .nunique() to see how many unique values in the column

array(['History', 'Math', 'Physics'], dtype=object)

In [ ]:
df=pd.get_dummies(df,columns=["course_name"],drop_first=True)
# we used drop_firts to avoid dummy variable, if we have n unique variables in the column we can represent them with n-1 dummy variables
# or u can use label encoder
_="""
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["course_name"]=le.fit_transform(df["course_name"])
"""

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   class_number         1615 non-null   int64
 1   study_hours          1615 non-null   float64
 2   last_exam_score      1615 non-null   int64
 3   exam_score           1615 non-null   int64
 4   course_name_Math     1615 non-null   bool
 5   course_name_Physics  1615 non-null   bool
dtypes: bool(2), float64(1), int64(3)
memory usage: 53.8 KB

In [71]:
# check if there any null values in the dataset
df.isnull().sum()

class_number           0
study_hours            0
last_exam_score        0
exam_score             0
course_name_Math       0
course_name_Physics    0
dtype: int64

In [72]:
df.head(10)

,class_number,study_hours,last_exam_score,exam_score,course_name_Math,course_name_Physics
0,1,4.1,65,61,False,False
1,2,9.5,65,95,True,False
2,3,7.5,55,90,True,False
3,1,6.2,72,80,False,False
4,2,2.0,56,45,False,True
5,3,2.0,38,36,False,False
6,3,1.0,81,32,False,True
7,1,9.0,79,100,True,False
8,1,6.2,94,76,True,False
9,3,7.2,50,77,False,True

In [73]:
y=df["exam_score"]
x=df.drop(["exam_score"],axis=1)

Linear regression example

In [74]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.6,random_state=42)

In [75]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [76]:
lr.fit(x_train,y_train)

LinearRegression()

In [77]:
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9806977791288921

In [78]:
df["predict"]=lr.predict(x)

In [79]:
df.head(10)

,class_number,study_hours,last_exam_score,exam_score,course_name_Math,course_name_Physics,predict
0,1,4.1,65,61,False,False,58.300379
1,2,9.5,65,95,True,False,97.282248
2,3,7.5,55,90,True,False,83.558612
3,1,6.2,72,80,False,False,73.291559
4,2,2.0,56,45,False,True,43.352532
5,3,2.0,38,36,False,False,44.155230
6,3,1.0,81,32,False,True,37.388203
7,1,9.0,79,100,True,False,93.400967
8,1,6.2,94,76,True,False,73.889646
9,3,7.2,50,77,False,True,80.635241

Compare Linear Models

In [82]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
models=[
    LinearRegression(),
    Ridge(),
    Lasso()
]

def evaluateModels():
    for x in models:
        model=x
        model.fit(x_train,y_train)
        score=model.score(x_test,y_test)
        name=x.__class__.__name__
        print(name,score)

evaluateModels()

LinearRegression 0.9806977791288921
Ridge 0.9806992814514716
Lasso 0.9798031130156238